import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Map from "../../components/imgs/map.png"
import Contact from '../../components/homepage-components/Contact'
import AboutHeader from '../../components/about-components/AboutHeader'
import SendMessage from '../../components/contact-componets/SendMessage'
import Address from '../../components/contact-componets/Address'
import Footer from '../../components/Footer'
import ChatBox from '../../components/contact-componets/ChatBox'
const index = () => {
  return (
    <div>
        <Head>
        <title>Techdev Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='space-y-5 '>
      <AboutHeader />
       <Address />
       <ChatBox />

       <SendMessage />


      

      <Footer />
      </main>
      
      </div>
  )
}

export default index