import React from 'react'
import Head from 'next/head'
import ServiceHeader from '../../components/services-component/ServiceHeader'
import Footer from '../../components/Footer'
import Contact from '../../components/homepage-components/Contact'
import Feedback from '../../components/homepage-components/Feedback'
import Faqs from '../../components/homepage-components/Faqs'
import FaqBanner from '../../components/homepage-components/FaqBanner'
import ShowcaseSlide from '../../components/ShowcaseSlide'
import ShowCase from '../../components/homepage-components/ShowCase'

const index = () => {
  return (
    <div>
        <Head>
        <title>Techdev Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-[1920px] flex flex-col'>
        <ServiceHeader type={"nobanner"} />
        {/* <ShowcaseSlide /> */}
        <ShowCase />
        <FaqBanner />
        <Feedback />
        <Contact />
        <Footer />
      </main>
    </div>
    
  )
}

export default index