import React from 'react'
import Head from 'next/head'
import ServiceHeader from '../../components/services-component/ServiceHeader'
import Footer from '../../components/Footer'
import Contact from '../../components/homepage-components/Contact'
import Feedback from '../../components/homepage-components/Feedback'
import FaqBanner from '../../components/homepage-components/FaqBanner'
import ShowCase from '../../components/homepage-components/ShowCase'
import AgencyCardsSection from '../../components/services-component/AgencyCardsSection'
import ServicesStack from '../../components/services-component/ServicesStack'
import Business from '../../components/services-component/Business'

const index = () => {
  return (
    <div>
        <Head>
        <title>Techdev Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='max-w-[1920px] flex flex-col'>
        <ServiceHeader type={"nobanner"} />
        <AgencyCardsSection />
        <ServicesStack />

        <ShowCase />
        <Feedback services />
        <Business />
        <Footer />
      </main>
    </div>
    
  )
}

export default index