import React from 'react'
import Head from 'next/head'
import ServiceHeader from '../../components/services-component/ServiceHeader'
import Footer from '../../components/Footer'
import Contact from '../../components/homepage-components/Contact'
import Feedback from '../../components/homepage-components/Feedback'
import FaqBanner from '../../components/homepage-components/FaqBanner'
import ShowCase from '../../components/homepage-components/ShowCase'
import AboutHeader from '../../components/about-components/AboutHeader'
import AboutStatement from '../../components/about-components/AboutStatement'
import Mission from '../../components/about-components/Mission'
import Team from '../../components/about-components/Team'
import QualityTestimonial from '../../components/about-components/QualityTestimonial'

const index = () => {
  return (
    <div>
        <Head>
        <title>Techdev About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='transition-all duration-300 flex flex-col'>
        <AboutHeader />
        <AboutStatement />
        <Mission />
        <Team />
        <ShowCase />
        {/* <QualityTestimonial /> */}
        <Footer />
      </main>
    </div>
    
  )
}

export default index