import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'
import AboutBanner from '../components/homepage-components/AboutBanner'
import Contact from '../components/homepage-components/Contact'
import FaqBanner from '../components/homepage-components/FaqBanner'
import Feedback from '../components/homepage-components/Feedback'
import Hero from '../components/homepage-components/Hero'
import Partners from '../components/homepage-components/Partners'
import ServiceList from '../components/homepage-components/ServiceList'
import ShowCase from '../components/homepage-components/ShowCase'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Techdev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
      <div className=''>

      <Hero />
      <AboutBanner />
      <Partners />
      <ServiceList />
      <ShowCase type={""} />
      <FaqBanner />
      <Feedback />
      <Contact />
      <Footer />
      </div>
      </>
    </div>
  )
}
